[colors.bright]
black = "#323232"
blue = "#addef8"
cyan = "#8affff"
green = "#a0e6af"
magenta = "#fe78ff"
red = "#ff9898"
white = "#ffffff"
yellow = "#feff57"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#242424"
blue = "#a978f6"
cyan = "#8afeff"
green = "#a0e6af"
magenta = "#fd56f9"
red = "#ff8989"
white = "#fefefe"
yellow = "#f0c674"

[colors.primary]
background = "#161616"
foreground = "#f8f8f6"
