[colors.bright]
black = "0x323232"
blue = "0xaddef8"
cyan = "0x8affff"
green = "0xa0e6af"
magenta = "0xfe78ff"
red = "0xff9898"
white = "0xffffff"
yellow = "0xfeff57"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "0x242424"
blue = "0xa978f6"
cyan = "0x8afeff"
green = "0xa0e6af"
magenta = "0xfd56f9"
red = "0xff8989"
white = "0xfefefe"
yellow = "0xf0c674"

[colors.primary]
background = "0x161616"
foreground = "0xf8f8f6"
