schemes:
  macaroni: &macaroni
    primary:
      background: '0x101010'
      foreground: '0xf8f8f6'
    normal:
      black:   '0x242424'
      red:     '0xff8989'
      green:   '0xf2ff8a'
      yellow:  '0xfefa67'
      blue:    '0xa978f6'
      magenta: '0xfd56f9'
      cyan:    '0x8afeff'
      white:   '0xfefefe'
    bright:
      black:   '0x323232'
      red:     '0xff9898'
      green:   '0xf7ff9f'
      yellow:  '0xfeff57'
      blue:    '0xaddef8'
      magenta: '0xfe78ff'
      cyan:    '0x8affff'
      white:   '0xffffff'

  snowy: &snowy
    primary:
      background: '#f6f6f6'
      foreground: '#262626'
    normal:
      black:   '#404040'
      red:     '#e68383'
      green:   '#a0e6af'
      yellow:  '#ffcd96'
      blue:    '#83b4e6'
      magenta: '#e1aae1'
      cyan:    '#8cd7d2'
      white:   '#dce6e6'
    bright:
      black:   '#404040'
      red:     '#e68383'
      green:   '#a0e6af'
      yellow:  '#ffcd96'
      blue:    '#83b4e6'
      magenta: '#e1aae1'
      cyan:    '#8cd7d2'
      white:   '#dce6e6'
  
  catppuccin: &catppuccin
    primary:
        background: "#24273A"
        foreground: "#CAD3F5"
    normal:
        black: "#494D64"
        red: "#ED8796"
        green: "#A6DA95"
        yellow: "#EED49F"
        blue: "#8AADF4"
        magenta: "#F5BDE6"
        cyan: "#8BD5CA"
        white: "#B8C0E0"
    bright:
        black: "#5B6078"
        red: "#ED8796"
        green: "#A6DA95"
        yellow: "#EED49F"
        blue: "#8AADF4"
        magenta: "#F5BDE6"
        cyan: "#8BD5CA"
        white: "#A5ADCB"

  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    normal:
      black: '#21222c'
      red: '#ff5555'
      green: '#50fa7b'
      yellow: '#f1fa8c'
      blue: '#bd93f9'
      magenta: '#ff79c6'
      cyan: '#8be9fd'
      white: '#f8f8f2'
    bright:
      black: '#6272a4'
      red: '#ff6e6e'
      green: '#69ff94'
      yellow: '#ffffa5'
      blue: '#d6acff'
      magenta: '#ff92df'
      cyan: '#a4ffff'
      white: '#ffffff'

  everforest: &everforest
    primary:
      background: '#2d353b'
      foreground: '#d3c6aa'
    normal:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'

  gruvbox: &gruvbox
    primary:
      background: '0x282828'
      foreground: '0xd4be98'
    normal:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'

  monochrome: &monochrome
    primary:
      background: "#000000"
      foreground: "#ffffff"
    cursor:
      text: "#000000"
      cursor: "#ffffff"
    normal:
      black: "#000000"
      red: "#6b6b6b"
      green: "#c4c4c4"
      yellow: "#b3b3b3"
      blue: "#999999"
      magenta: "#717171"
      cyan: "#8a8a8a"
      white: "#b5cabb"
    bright:
      black: "#202020"
      red: "#464646"
      green: "#f8f8f8"
      yellow: "#eeeeee"
      blue: "#7c7c7c"
      magenta: "#adadad"
      cyan: "#c0c0c0"
      white: "#99ac9e"

  nord: &nord
    primary:
      background: "#2e3440"
      foreground: "#d8dee9"
    normal:
      black: "#3b4252"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#88c0d0"
      white: "#e5e9f0"
    bright:
      black: "#4c566a"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#8fbcbb"
      white: "#eceff4"

  tokyonight: &tokyonight
    primary:
      background: '0x1a1b26'
      foreground: '0xc0caf5'
    normal:
      black:   '0x15161E'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xa9b1d6'
    bright:
      black:   '0x414868'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xc0caf5'

  vaporwave: &vaporwave
    primary:
      background: '#f3f3f3'
      foreground: '#424153'
    normal:
      black:   '#4b4646'
      red:     '#996633'
      green:   '#0abf0a'
      yellow:  '#dada00'
      blue:    '#333399'
      magenta: '#d7a0e6'
      cyan:    '#999999'
      white:   '#dddddd'
    bright:
      black:   '#4b4646'
      red:     '#996633'
      green:   '#0abf0a'
      yellow:  '#dada00'
      blue:    '#333399'
      magenta: '#d7a0e6'
      cyan:    '#999999'
      white:   '#dddddd'
  
  bloom: &bloom
    primary:
      background: '#fffaf5'
      foreground: '#4b4646'
    normal:
      black: '#4b4646'
      red: '#eb8c8c'
      green: '#96e6a5'
      yellow: '#f0cd96'
      blue: '#9bb9f0'
      magenta: '#d7a0e6'
      cyan: '#a0e1d2'
    bright:
      black: '#4b4646'
      red: '#eb8c8c'
      green: '#96e6a5'
      yellow: '#f0cd96'
      blue: '#9bb9f0'
      magenta: '#d7a0e6'
      cyan: '#a0e1d2'

colors: *macaroni
