[colors.bright]
black = "#323232"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#ffffff"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#242424"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#ffffff"
yellow = "#f9e2af"

[colors.primary]
background = "#161616"
foreground = "#f8f8f6"
