#!/bin/bash
./scripts/alacritty.sh
./scripts/docker.sh
./scripts/fonts.sh
./scripts/gvm.sh
./scripts/nvm.sh
./scripts/rust.sh
./scripts/neovim.sh
./scripts/tmux.sh
./scripts/tailscale.sh
./scripts/zsh.sh
